apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-config
  namespace: cert-manager
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 443 ssl;
        server_name cert-server.cert-manager.svc;

        # SSL Configuration
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        # Security Headers
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";

        # Certificates Directory
        location /certs {
          alias /usr/share/nginx/html/certs;
          autoindex off;
          allow all;

          # Restrict to GET requests only
          limit_except GET {
            deny all;
          }
        }

        # Health Check Endpoint
        location /healthz {
          allow all;
          return 200 "healthy\n";
        }

        # Default deny
        location / {
          return 403;
        }
      }
    }