apiVersion: v1
kind: Deployment
metadata:
  name: cert-server
  namespace: cert-manager
  labels:
    app: cert-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cert-server
  template:
    metadata:
      labels:
        app: cert-server
    spec:
      securityContext:
        fsGroup: 101
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: secret
          mountPath: /etc/nginx/ssl/
        - name: certs
          mountPath: /usr/share/nginx/html/certs
        livenessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: nginx-https-config
      - name: secret
        secret:
          secretName: nginx-certs-tls
      - name: certs
        persistentVolumeClaim:
          claimName: shared-certificates-pvc
